spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/demo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: demo_user
    password: demo_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080

logging:
  level:
    com.pgr.sb.docker: INFO