hibernate:
  format_sql: 'true'
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/demo
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

server:
  port: 8080
logging:
  level:
    com.banking: DEBUG
    org.springframework.security: DEBUG
